changelog:
  categories:
    - title: Breaking Changes 📢
      labels:
        - major
    - title: New Features 💡
      labels:
        - minor
    - title: Patches 🩹
      labels:
        - patch
    - title: Documentation 📝
      labels:
        - docs
    - title: Other Changes
      labels:
        - "*"
