repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 2c9f875913ee60ca25ce70243dc24d5b6415598c # frozen: v4.6.0
    hooks:
      # check file system problems
      - id: check-case-conflict
      - id: check-symlinks
      - id: destroyed-symlinks

      # unify whitespace and line ending
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: mixed-line-ending

      # sort requirements.txt files
      - id: requirements-txt-fixer

      # check more
      - id: check-yaml
      - id: check-toml
      - id: check-xml
      - id: check-executables-have-shebangs
      - id: check-merge-conflict

  - repo: https://github.com/python-poetry/poetry
    rev: "c85477da8a610a87133299f996f8d8a593aa7bff" # frozen: 1.8.0
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args: ["--no-update"]
        files: ^pyproject\.toml|poetry\.lock$

  - repo: https://github.com/floatingpurr/sync_with_poetry
    rev: 41b6bf233c52f08f344e09107bdda253e6d8b57a # frozen: 1.1.0
    hooks:
      - id: sync_with_poetry
        files: ^\.pre-commit-config\.yaml|poetry\.lock$
        pass_filenames: false
        args:
          - "poetry.lock"
          - "--allow-frozen"
          - "--db"
          - "swp.json"

  # Enforce frozen revisions in `.pre-commit-config.yaml`
  - repo: https://github.com/real-yfprojects/check-pre-commit-config
    rev: ec697f7fda57bd81b86556212539e22f03aa86d9 # frozen: v1.0.0-alpha4
    hooks:
      - id: check-frozen
        args:
          - "--rules"
          - "ycamfte"
          - "--fix-all"

  # Lint python code with ruff (also sorts imports)
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "bbaf495f2dc6ce2853c91dc0b2c75d3b8249c15c" # frozen: v0.1.15
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  # Format python code with black
  - repo: https://github.com/psf/black
    rev: ec91a2be3c44d88e1a3960a4937ad6ed3b63464e # frozen: 23.12.1
    hooks:
      - id: black

  # Static type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: e5ea6670624c24f8321f6328ef3176dbba76db46 # frozen: v1.10.0
    hooks:
      - id: mypy
        exclude: ^(tests|docs)
        args: [--ignore-missing-imports]

  # format many other files with prettier
  - repo: "https://github.com/pycontribs/mirrors-prettier"
    rev: b28ab1718b516827e9f6cdfbd3c4c9546489d53e # frozen: v3.3.2
    hooks:
      - id: prettier
        exclude: ^docs/(sphinx/_)templates/

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: bea368871c59605bf2471441d0c6214bd3b80c44 # frozen: v0.18
    hooks:
      - id: validate-pyproject
        files: pyproject.toml$

# configuration for the pre-commit.ci bot
# only relevant when actually using the bot
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit hooks

    for more information, see https://pre-commit.ci, https://pre-commit.com and
    the `.pre-commit-config.yaml` file in this repository.

  autofix_prs: true # default
  autoupdate_branch: "develop"
  autoupdate_commit_msg: |
    [pre-commit.ci] Autoupdate pre-commit hook versions.

    for more information, see https://pre-commit.ci, https://pre-commit.com and
    the `.pre-commit-config.yaml` file in this repository.

  submodules: false # default
